# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [45]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [46]:
print(np.__version__)
np.__config__.show()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [47]:
m = np.zeros(10)
print(m)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [48]:
import numpy as np
m = np.array([11,22,33,44,55,66,77])
print(m.size)       # size of array
print(m.itemsize)   # size of numpy array

7
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [49]:
np.info(np)       # provides numpy documentation
np.info(np.add)   # provides numpy-add function documentation

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [50]:
b = np.zeros(10)
b[4] = 1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [51]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [52]:
n = ["Cat","is","cute","pet"]
n[::-1]

['pet', 'cute', 'is', 'Cat']

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [53]:
mat = np.arange(0,9)
print(mat.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [54]:
z = [1,2,0,0,4,0]
np.nonzero(z)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [55]:
a = np.eye(3, dtype = int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [56]:
np.random.random((3,3,3))

array([[[0.91725361, 0.07764938, 0.15908257],
        [0.62871071, 0.50894856, 0.73392223],
        [0.43915691, 0.22265541, 0.08278579]],

       [[0.55399421, 0.11510915, 0.49382153],
        [0.57723958, 0.04972277, 0.64813057],
        [0.75164169, 0.41245185, 0.78784315]],

       [[0.53354698, 0.29520543, 0.96275779],
        [0.43799043, 0.37738611, 0.4287982 ],
        [0.84424648, 0.06833714, 0.09021135]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [57]:
import numpy as np
mat = np.random.random((10,10))
print("min -->" , np.min(mat))
print("Max -->" , np.max(mat))

min --> 0.005429969476878016
Max --> 0.9892609887446911


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [58]:
import numpy as np
b = np.random.rand(30)
print(b)
np.mean(b)  # mean value of rand(30)

[0.81546679 0.88704985 0.73590656 0.30838178 0.33736948 0.99031864
 0.42816656 0.50422883 0.0862342  0.16002081 0.21907551 0.53948249
 0.21554976 0.55960232 0.71314671 0.81224559 0.67668872 0.84890087
 0.80222317 0.25406253 0.0934788  0.27717829 0.47977207 0.86583695
 0.55824783 0.64498366 0.56403989 0.62018069 0.54713631 0.57496615]


0.537331393249272

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [59]:
L = np.ones((6,6))
L[1:-1, 1:-1] = 0
print(L)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [60]:
L = np.ones((6,6))
M = np.pad(array = L, pad_width = 1, mode = 'constant')
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [61]:
print(0 * np.nan,
      np.nan == np.nan,
      np.inf > np.nan,
      np.nan - np.nan,
      0.3 == 3 * 0.1)

nan False False nan False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [62]:
c = np.diag( 1+np.arange(4), k = -1)
print(c)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [63]:
y = np.zeros((8,8) , dtype=int)
y[1::2 , ::2] = 1
y[::2 , 1::2] = 1
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [64]:
ind = ( np.unravel_index(100, (6,7,8)) )
ind

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [65]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(n)

['Cat', 'is', 'cute', 'pet']


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [66]:
h = np.random.random((5,5))
h = (h - np.mean (h)) / (np.std (h))
print(h)

[[-0.7375724  -0.02186563 -0.93697081  0.16082915  0.63215553]
 [ 0.88750134  1.62636583 -0.06594841  1.34915938 -0.72575319]
 [ 0.32607619  0.32732431 -0.30876645 -0.06572385  0.76150035]
 [-1.66542653  0.40005718 -1.01870834  1.52023123 -0.32496888]
 [-1.66599812  1.40906992 -1.77633885 -1.08397678  0.99774782]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [67]:
color = np.dtype([("a", np.ubyte),
                  ("y", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte)])
color

dtype([('a', 'u1'), ('y', 'u1'), ('g', 'u1'), ('b', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [68]:
mat = np.dot(np.ones((5,3)) , np.ones((3,2)))
print(mat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [69]:
a = np.arange(11)
a[(a > 3) & (a <= 7)] = -1
print(a)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [70]:
# 9
# 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [71]:
'''
Legal:
      Z**Z
      2 << Z >> 2
      Z <- Z
      1j*Z
      Z/1/1
'''
''' Z<Z>Z ---> val error '''

' Z<Z>Z ---> val error '

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [72]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-72-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-72-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [73]:
x = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(x)),x))  

[ 9.  9. -2.  2.  2. -6.  3.  5. -9.  3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [74]:
a = np.arange(0,10)
b = np.arange(5,15)
print(np.intersect1d(a,b))

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [75]:
defaults = np.seterr(all="ignore")
X = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [76]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-76-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [77]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today     = np.datetime64('today', 'D')
print(today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2023-02-08
2023-02-09
2023-02-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [78]:
x = np.arange('2016-07', '2016-08', dtype ='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [79]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [80]:
s = np.random.uniform(0,25,10)

print(s - s%1)
print(np.floor(s))
print(np.ceil(s)-1)
print(s.astype(int))
print(np.trunc(s))

[ 5. 13.  8.  4. 24. 20. 22.  0.  6. 20.]
[ 5. 13.  8.  4. 24. 20. 22.  0.  6. 20.]
[ 5. 13.  8.  4. 24. 20. 22.  0.  6. 20.]
[ 5 13  8  4 24 20 22  0  6 20]
[ 5. 13.  8.  4. 24. 20. 22.  0.  6. 20.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [81]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [82]:
def generate_integers():
    for i in range(10):
        yield i
x = np.fromiter(generate_integers(), dtype=np.float32, count = -1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [83]:
m = np.linspace(0,1,11,endpoint=False)[1:]
print(m)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [84]:
import numpy as np
np.random.random(10)

array([0.62495874, 0.30381782, 0.5338891 , 0.25873987, 0.18896487,
       0.9621733 , 0.44585974, 0.92657606, 0.21749766, 0.57378156])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [85]:
import time

begin_time = time.time()
x = np.arange(100000)
np.sum(x)
print("Time taken using np.sum")
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(100000)
np.add.reduce(x)
print("Time take using np.add.reduce")
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

Time taken using np.sum
0.5426406860351562
Time take using np.add.reduce
4.965543746948242


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [86]:
C = np.random.randint(0,7,1)
D = np.random.randint(0,7,1)

# Using np.allclose
equal = np.allclose(C,D)
print(equal)

# Using np.array_equal
equal = np.array_equal(C,D)
print(equal)

True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [87]:
z = np.ones(10)
z.flags.writeable = False
z[0] = 1 # -> Value ERROR

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [88]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
L = np.sqrt(X**2+Y**2)
M = np.arctan2(Y,X)
print(L)
print(M)

[0.06966694 0.48932167 0.7498477  0.55165622 0.68837848 0.51060622
 1.04983229 0.22029763 1.0001237  0.70186697]
[0.28676936 0.41990373 0.81327501 1.51741683 1.02375067 1.5698112
 0.90006744 0.1649971  0.1855536  0.39593284]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [91]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.66536536 0.08554243 0.16216703 0.1445294  0.27253305 0.69140954
 0.         0.17433317 0.57600175 0.39021813]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [92]:
a = np.zeros((4,4), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid (np.linspace(0,1,4), np.linspace(0,1,4))
print(a)

[[(0.        , 0.        ) (0.33333333, 0.        )
  (0.66666667, 0.        ) (1.        , 0.        )]
 [(0.        , 0.33333333) (0.33333333, 0.33333333)
  (0.66666667, 0.33333333) (1.        , 0.33333333)]
 [(0.        , 0.66666667) (0.33333333, 0.66666667)
  (0.66666667, 0.66666667) (1.        , 0.66666667)]
 [(0.        , 1.        ) (0.33333333, 1.        )
  (0.66666667, 1.        ) (1.        , 1.        )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [100]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [94]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [95]:
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
x = np.zeros((15,15))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [96]:
p = np.arange(100)
q = np.random.uniform(0,100)
index = (np.abs(p-q)).argmin()
print(p[index])

2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [97]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-97-1c50e4e32ac3>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [98]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy.spatial

Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.44475874 0.75726771 0.38263054 0.58404532 0.70349406 0.75363724 0.40003857 0.50339026 0.31804889 0.39334073 0.40727921 0.67389515 0.46150424 0.70165813 0.41122548 0.45461573 0.47322051 0.6878093  0.49649244 0.7161114  0.60280624 0.34854962 0.61292819 0.66173271 0.46005354 0.30567424 0.49702803 0.84221049 0.8317268  0.4468611  0.16483766 0.13088994 0.45794015 0.45346497 0.37346748 0.36101177 0.53573909 0.37358706 0.44533637 0.22438345 0.52939548 0.172748   0.19864938 0.57209854 0.5641903  0.11314556 0.57443709 0.55526013 0.44448951 0.5116948  0.11739883 0.52991059 0.02246482 0.84202478 0.44714413 0.59758953 0.39566654 0.59433395 0.35498694 0.51595218 0.12520201 0.81770197 0.77851431 0.4583812  0.07024542 0.36561015 0.58512031 0.30627905 0.63182869 0.46733911 0.33063869 0.65795692 0.11124942 0.34252337 0.8023769  0.63350752 0.42007396 0.43170053 0.35428693 0.79352906 0.4942557  0.44038354 0.76279406 0.61914238 0.51822859 0.52198111 0.86217351 0.10560997 0.31749153 0.290188

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [101]:
a = np.arange(15, dtype=np.float32)
a = a.astype(np.int32, copy=False)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [102]:
from io import StringIO

r = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
s = np.genfromtxt(r, delimiter=",", dtype=np.int)
print(s)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-102-6d3b4963d22c>:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = np.genfromtxt(r, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [103]:
Z = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [104]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x*x+y*y)
sigma, mu =1.0,0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [105]:
n = 7
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [106]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.17084364  0.08131437  0.19997058  0.4073446   0.25822134 -0.29735673 -0.14662959 -0.51259401 -0.1977698   0.37834288]
 [-0.22458242  0.42823973  0.42343086  0.58774393  0.04141342 -0.34568811 -0.32039012  0.02695874 -0.36981148 -0.24731455]
 [ 0.50861391  0.18405919 -0.17315054 -0.01553933 -0.0595804   0.15011504 -0.34558945  0.12130566 -0.05509617 -0.31513791]
 [ 0.31298865  0.0070511  -0.0312267  -0.35467806 -0.41407438  0.45470297 -0.02058369 -0.0579024   0.4408122  -0.33708969]
 [-0.08353236 -0.2960037   0.37934587 -0.18071331  0.12629643  0.00891014 -0.20009965  0.12008095  0.34971848 -0.22400285]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [107]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[6 2 1]
 [9 3 6]
 [8 8 2]]
[[6 2 1]
 [9 3 6]
 [8 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [108]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [109]:
x = np.random.uniform(0,1,10)
z = 0.5
m = x.flat[np.abs(x - z).argmin()]
print(m)

0.5210282020751682


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [110]:
m = np.arange(3).reshape(3,1)
n = np.arange(3).reshape(1,3)
it = np.nditer([m,n,None])
for m,n,o in it: o[...] = m + n
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [111]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(10), "range_10")
print (x.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [112]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)

np.add.at(x, y, 1)
print(x)

[1. 4. 3. 4. 1. 4. 3. 5. 3. 2.]
[1. 7. 5. 7. 1. 7. 5. 9. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [113]:
x = [1,2,3,4,5,6]
y = [1,3,5,7,9,1]
z = np.bincount(y,x)
print(z)

[0. 7. 0. 2. 0. 3. 0. 4. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [114]:
w, h = 144, 144
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [115]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 36 76 43]
 [57 59 52 35]
 [53 65 50 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [116]:
D = np.random.uniform(0,1,50)
S = np.random.randint(0,10,50)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52831472 0.34743603 0.93883249 0.64345721 0.49832848 0.71376219 0.52666614 0.92255029 0.37571713 0.47099868]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [117]:
X = np.random.uniform(0,1,(5,5))
Y = np.random.uniform(0,1,(5,5))

np.diag(np.dot(X, Y))

array([1.50691414, 1.42107382, 0.73601822, 0.66320484, 0.87359425])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [118]:
x = np.array([1,2,3,4,5])
y = 3
z = np.zeros(len(x) + (len(x)-1)*(y))
z[::4] = x
print(z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [119]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [121]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [122]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 69) ( 1, 89) (11, 20) (11, 67) (13, 16) (13, 90) (15, 27) (15, 55) (15, 67) (15, 75) (16, 90) (18, 24) (18, 32) (18, 35) (18, 78) (20, 67) (23, 26) (23, 84) (24, 78) (26, 84) (27, 67) (32, 35) (40, 54) (40, 93) (54, 56) (54, 93) (55, 75) (56, 93) (69, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [124]:
C = np.bincount([1,2,4,6,9,10])
A = np.repeat(np.arange(len(C)), C)
print(A)

[ 1  2  4  6  9 10]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [127]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [128]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [129]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 0 1 1 0]
Negating a boolean: 
[0 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 1]
original: 
[-0.45342378  0.12440436  0.91397495 -0.16342743 -0.98698839  0.9885842  -0.35310558 -0.51675177  0.12591936 -0.70852995]
Change the sign of float inplace: 
[ 0.45342378 -0.12440436 -0.91397495  0.16342743  0.98698839 -0.9885842   0.35310558  0.51675177 -0.12591936  0.70852995]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [130]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.4449227   2.95823935  8.34807982 19.53742197 13.45298084  7.49740057 17.10007781 19.23664277  1.11398526 11.92477   ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [134]:
P0 = np.random.uniform(-6, 6, (6,2))
P1 = np.random.uniform(-6,6,(6,2))
p = np.random.uniform(-6, 6, (6,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.64099623  7.63518218  1.85762284  3.35427387  3.84667453  2.30079622]
 [ 0.59165506  9.32567368  7.63650618  5.46830191  5.02211584  6.44972235]
 [ 4.31233585  2.04593366  3.93735354  5.24844706  0.33637516  0.9243983 ]
 [ 4.72527746  9.80144802  1.53173172  0.96411845  0.23140216  1.32250784]
 [ 1.16345861 10.31287148  8.2933017   5.65572451  5.88577261  7.33318191]
 [ 3.52138172  0.69705471  1.84842891  0.70427811  6.23335129  4.95558065]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [133]:
Z = np.random.randint(0,4,(4,4))
shape = (2,2)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 2 3 0]
 [1 0 3 1]
 [1 2 2 1]
 [1 2 1 1]]
[[0 2]
 [1 0]]


<ipython-input-133-5863784b11ba>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [135]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [137]:
Z = np.random.uniform(0,1,(5,5))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-4)
print(rank)

5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [139]:
a = np.random.randint(0,1,5)
print(np.bincount(a).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [151]:
Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 2 0]
   [0 0 2]
   [2 0 3]]

  [[2 0 1]
   [0 2 2]
   [0 3 1]]

  [[0 1 2]
   [2 2 1]
   [3 1 2]]

  [[1 2 2]
   [2 1 1]
   [1 2 3]]]


 [[[0 0 2]
   [2 0 3]
   [3 1 1]]

  [[0 2 2]
   [0 3 1]
   [1 1 1]]

  [[2 2 1]
   [3 1 2]
   [1 1 3]]

  [[2 1 1]
   [1 2 3]
   [1 3 2]]]


 [[[2 0 3]
   [3 1 1]
   [4 3 4]]

  [[0 3 1]
   [1 1 1]
   [3 4 4]]

  [[3 1 2]
   [1 1 3]
   [4 4 1]]

  [[1 2 3]
   [1 3 2]
   [4 1 3]]]


 [[[3 1 1]
   [4 3 4]
   [2 2 2]]

  [[1 1 1]
   [3 4 4]
   [2 2 3]]

  [[1 1 3]
   [4 4 1]
   [2 3 0]]

  [[1 3 2]
   [4 1 3]
   [3 0 0]]]]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [152]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[1,3] = 42
print(S)

[[ 1  2 11 10  5]
 [ 2  7 15 42  6]
 [11 15  4  8 14]
 [10 42  8  5  9]
 [ 5  6 14  9  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [148]:
p, n = 20, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [149]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [150]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [153]:
x = np.arange(10000)
np.random.shuffle(x)
n = 4
print (x[np.argpartition(-x,n)[:n]]) #(Z[np.argsort(Z)[-n:]])

[9997 9999 9998 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [155]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 11, 21], [4, 5], [6, 7])))

[[ 1  4  6]
 [ 1  4  7]
 [ 1  5  6]
 [ 1  5  7]
 [11  4  6]
 [11  4  7]
 [11  5  6]
 [11  5  7]
 [21  4  6]
 [21  4  7]
 [21  5  6]
 [21  5  7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [157]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [158]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [159]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 3 1]
 [2 3 0]
 [0 4 1]
 [4 1 2]
 [3 2 4]
 [4 1 1]
 [3 0 0]
 [1 0 4]
 [3 4 1]
 [2 0 1]]
[[2 3 1]
 [2 3 0]
 [0 4 1]
 [4 1 2]
 [3 2 4]
 [4 1 1]
 [3 0 0]
 [1 0 4]
 [3 4 1]
 [2 0 1]]
[[2 3 1]
 [2 3 0]
 [0 4 1]
 [4 1 2]
 [3 2 4]
 [4 1 1]
 [3 0 0]
 [1 0 4]
 [3 4 1]
 [2 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [160]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [161]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [164]:
m = np.random.uniform(0,1,6)
n = np.random.uniform(0,1,6)

np.einsum('i->', m)           # np.sum(m)
np.einsum('i,i->i', m, n)     # m * n
np.einsum('i,i', m, n)        # np.inner(m, n)
np.einsum('i,j->ij', m, n)    # np.outer(m, n)

array([[0.46681508, 0.20732933, 0.44789791, 0.47893292, 0.39594291, 0.24932071],
       [0.57731182, 0.25640489, 0.55391688, 0.59229798, 0.48966396, 0.30833578],
       [0.6521162 , 0.2896282 , 0.62568989, 0.66904417, 0.55311149, 0.34828796],
       [0.88844473, 0.39459018, 0.85244146, 0.91150744, 0.75356047, 0.47450838],
       [0.33759869, 0.14993969, 0.32391786, 0.34636225, 0.28634423, 0.18030768],
       [0.09162374, 0.04069339, 0.08791079, 0.09400216, 0.07771337, 0.04893522]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [165]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [166]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [168]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24600197  0.2116081 ]
